name: Deploy

# Only deploy the main branch.
on:
  push:
      branches:
        - main

jobs:
  Deploy:
    name: Deploy Production
    runs-on: [self-hosted, webserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          mkdir -p /var/www/api.retr0.dev/
          sudo cp -a $GITHUB_WORKSPACE/. /var/www/api.retr0.dev/
  Build:
     name: Compile
     needs: Deploy
     runs-on: [self-hosted, webserver]
     if: startsWith( github.event.commits[0].message, '[BUILD]' ) 
     steps:
       - name: Compile & Start
         run: |
           cd /var/www/api.retr0.dev
           npm install
           npm run build
           npm run start
          
