name: Deploy

# Only deploy the main branch.
on:
  push:
      branches:
        - main

jobs:
  Deploy:
    name: Deploy to Production
    runs-on: [self-hosted, webserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          clean: false
      - name: Deploy
        run: |
          sudo cp -a $GITHUB_WORKSPACE/. /var/www/api.spaceretr0.com/
          cd /var/www/api.spaceretr0.com
          